version: '2'
services:

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      - "NATS_SERVER=${NATS_SERVER}"
    logging:
        driver: "json-file"
        options:
            max-size: 100m
            max-file: "5"

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.0.0"
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - "./es/data:/usr/share/elasticsearch/data"
      - "./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"

  kibana:
    image: "docker.elastic.co/kibana/kibana:6.0.0"
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - "./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml"

